### ISSUE TITLE
pin dependencies

### ISSUE THREAD

**Issue by dfroger** [conda-forge/sqlalchemy-migrate-feedstock#1]
Dependencies should be pinned as in [requirements.txt](https://github.com/openstack/sqlalchemy-migrate/blob/0.9.4/requirements.txt).

I'm working on a recipe for buildbot, and I have this kind of errors during tests at runtime:

```
$ buildbot create-master master

Traceback (most recent call last):
  File "/home/dfroger/miniconda3/conda-bld/buildbot_1495624299918/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/home/dfroger/miniconda3/conda-bld/buildbot_1495624299918/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dfroger/miniconda3/conda-bld/buildbot_1495624299918/_t_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pbr 3.0.0 (/home/dfroger/miniconda3/conda-bld/buildbot_1495624299918/_t_env/lib/python3.6/site-packages), Requirement.parse('pbr<1.0,>=0.5.21'), {'sqlalchemy-migrate'})

```

(edit: PR coming...)

**Comment by dfroger** [comment]
I commited [here](https://github.com/dfroger/sqlalchemy-migrate-feedstock/commit/ba2674b61efed57ac3fae65a7cc31f2939658e80), but need a `pbr 0.5.21,<1.0` version in conda-forge first

**Comment by mariusvniekerk** [comment]
You mean pbr >=0.5.2

**Comment by dfroger** [comment]
yes thanks, I've fixed it. Seems that `pbr` will be missing for Python 3.5 and Python 3.6

**Comment by dfroger** [comment]
There are other errrors `ImportError: No module named testrepository` I don't understand for now. Will try later...
